// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/daily_reward_state.dart';
import 'data/models/player_progress.dart';
import 'data/models/settings_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 695088743465370516),
    name: 'DailyRewardState',
    lastPropertyId: const obx_int.IdUid(4, 1608846059587771486),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8406010299724138512),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3313531032877894796),
        name: 'currentStreakDay',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2462351603623946138),
        name: 'lastClaimDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1608846059587771486),
        name: 'claimedToday',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5721975297453377701),
    name: 'PlayerProgress',
    lastPropertyId: const obx_int.IdUid(15, 7954988184269641489),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3173678590950932549),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5141205898043676829),
        name: 'normalHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5852972910858267399),
        name: 'hardHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2415869980273436639),
        name: 'ultraHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6073628706487738678),
        name: 'hints',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5956125930848638052),
        name: 'extraLives',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3227337024713281160),
        name: 'undos',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3131882955628838766),
        name: 'bulbs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2701891915401600914),
        name: 'tutorialSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1224557861632085792),
        name: 'lastRuleTutorialLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1100188890406525148),
        name: 'diagonalRuleSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2413943962156181175),
        name: 'minDistanceRuleSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3685575093260790641),
        name: 'knightMoveRuleSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 613559806886336316),
        name: 'adsRemoved',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7954988184269641489),
        name: 'levelsCompletedCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2045880825227824889),
    name: 'SettingsModel',
    lastPropertyId: const obx_int.IdUid(5, 526746762152375839),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6446526463243470978),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3469116826683986884),
        name: 'musicVolume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5891764849343042463),
        name: 'sfxVolume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6760770555663876785),
        name: 'selectedThemeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 526746762152375839),
        name: 'vibrationEnabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 2045880825227824889),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DailyRewardState: obx_int.EntityDefinition<DailyRewardState>(
      model: _entities[0],
      toOneRelations: (DailyRewardState object) => [],
      toManyRelations: (DailyRewardState object) => {},
      getId: (DailyRewardState object) => object.id,
      setId: (DailyRewardState object, int id) {
        object.id = id;
      },
      objectToFB: (DailyRewardState object, fb.Builder fbb) {
        final lastClaimDateOffset = fbb.writeString(object.lastClaimDate);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.currentStreakDay);
        fbb.addOffset(2, lastClaimDateOffset);
        fbb.addBool(3, object.claimedToday);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DailyRewardState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..currentStreakDay = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..lastClaimDate = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..claimedToday = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          );

        return object;
      },
    ),
    PlayerProgress: obx_int.EntityDefinition<PlayerProgress>(
      model: _entities[1],
      toOneRelations: (PlayerProgress object) => [],
      toManyRelations: (PlayerProgress object) => {},
      getId: (PlayerProgress object) => object.id,
      setId: (PlayerProgress object, int id) {
        object.id = id;
      },
      objectToFB: (PlayerProgress object, fb.Builder fbb) {
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.normalHighest);
        fbb.addInt64(2, object.hardHighest);
        fbb.addInt64(3, object.ultraHighest);
        fbb.addInt64(4, object.hints);
        fbb.addInt64(5, object.extraLives);
        fbb.addInt64(6, object.undos);
        fbb.addInt64(7, object.bulbs);
        fbb.addBool(8, object.tutorialSeen);
        fbb.addInt64(9, object.lastRuleTutorialLevel);
        fbb.addBool(10, object.diagonalRuleSeen);
        fbb.addBool(11, object.minDistanceRuleSeen);
        fbb.addBool(12, object.knightMoveRuleSeen);
        fbb.addBool(13, object.adsRemoved);
        fbb.addInt64(14, object.levelsCompletedCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlayerProgress()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..normalHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..hardHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..ultraHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..hints = const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
          ..extraLives = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..undos = const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
          ..bulbs = const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
          ..tutorialSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..lastRuleTutorialLevel = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..diagonalRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            24,
            false,
          )
          ..minDistanceRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          )
          ..knightMoveRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..adsRemoved = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            30,
            false,
          )
          ..levelsCompletedCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            32,
            0,
          );

        return object;
      },
    ),
    SettingsModel: obx_int.EntityDefinition<SettingsModel>(
      model: _entities[2],
      toOneRelations: (SettingsModel object) => [],
      toManyRelations: (SettingsModel object) => {},
      getId: (SettingsModel object) => object.id,
      setId: (SettingsModel object, int id) {
        object.id = id;
      },
      objectToFB: (SettingsModel object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.musicVolume);
        fbb.addFloat64(2, object.sfxVolume);
        fbb.addInt64(3, object.selectedThemeIndex);
        fbb.addBool(4, object.vibrationEnabled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SettingsModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..musicVolume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..sfxVolume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..selectedThemeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..vibrationEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DailyRewardState] entity fields to define ObjectBox queries.
class DailyRewardState_ {
  /// See [DailyRewardState.id].
  static final id = obx.QueryIntegerProperty<DailyRewardState>(
    _entities[0].properties[0],
  );

  /// See [DailyRewardState.currentStreakDay].
  static final currentStreakDay = obx.QueryIntegerProperty<DailyRewardState>(
    _entities[0].properties[1],
  );

  /// See [DailyRewardState.lastClaimDate].
  static final lastClaimDate = obx.QueryStringProperty<DailyRewardState>(
    _entities[0].properties[2],
  );

  /// See [DailyRewardState.claimedToday].
  static final claimedToday = obx.QueryBooleanProperty<DailyRewardState>(
    _entities[0].properties[3],
  );
}

/// [PlayerProgress] entity fields to define ObjectBox queries.
class PlayerProgress_ {
  /// See [PlayerProgress.id].
  static final id = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[0],
  );

  /// See [PlayerProgress.normalHighest].
  static final normalHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[1],
  );

  /// See [PlayerProgress.hardHighest].
  static final hardHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[2],
  );

  /// See [PlayerProgress.ultraHighest].
  static final ultraHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[3],
  );

  /// See [PlayerProgress.hints].
  static final hints = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[4],
  );

  /// See [PlayerProgress.extraLives].
  static final extraLives = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[5],
  );

  /// See [PlayerProgress.undos].
  static final undos = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[6],
  );

  /// See [PlayerProgress.bulbs].
  static final bulbs = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[7],
  );

  /// See [PlayerProgress.tutorialSeen].
  static final tutorialSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[8],
  );

  /// See [PlayerProgress.lastRuleTutorialLevel].
  static final lastRuleTutorialLevel = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[9],
  );

  /// See [PlayerProgress.diagonalRuleSeen].
  static final diagonalRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[10],
  );

  /// See [PlayerProgress.minDistanceRuleSeen].
  static final minDistanceRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[11],
  );

  /// See [PlayerProgress.knightMoveRuleSeen].
  static final knightMoveRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[12],
  );

  /// See [PlayerProgress.adsRemoved].
  static final adsRemoved = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[13],
  );

  /// See [PlayerProgress.levelsCompletedCount].
  static final levelsCompletedCount = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[14],
  );
}

/// [SettingsModel] entity fields to define ObjectBox queries.
class SettingsModel_ {
  /// See [SettingsModel.id].
  static final id = obx.QueryIntegerProperty<SettingsModel>(
    _entities[2].properties[0],
  );

  /// See [SettingsModel.musicVolume].
  static final musicVolume = obx.QueryDoubleProperty<SettingsModel>(
    _entities[2].properties[1],
  );

  /// See [SettingsModel.sfxVolume].
  static final sfxVolume = obx.QueryDoubleProperty<SettingsModel>(
    _entities[2].properties[2],
  );

  /// See [SettingsModel.selectedThemeIndex].
  static final selectedThemeIndex = obx.QueryIntegerProperty<SettingsModel>(
    _entities[2].properties[3],
  );

  /// See [SettingsModel.vibrationEnabled].
  static final vibrationEnabled = obx.QueryBooleanProperty<SettingsModel>(
    _entities[2].properties[4],
  );
}
