// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../data/models/daily_challenge_state.dart';
import '../../data/models/daily_reward_state.dart';
import '../../data/models/player_progress.dart';
import '../../data/models/settings_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4370168794124197122),
    name: 'DailyRewardState',
    lastPropertyId: const obx_int.IdUid(4, 4290983376059355038),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1459133958021992578),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4580897389184361288),
        name: 'currentStreakDay',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6849963347669569467),
        name: 'lastClaimDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4290983376059355038),
        name: 'claimedToday',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3079320991520534107),
    name: 'PlayerProgress',
    lastPropertyId: const obx_int.IdUid(15, 8626051969272955424),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1338959543473581982),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5340698426127719809),
        name: 'normalHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5940032039324559731),
        name: 'hardHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7549169434530044980),
        name: 'ultraHighest',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4748831320157891971),
        name: 'hints',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6476433726047124486),
        name: 'extraLives',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2546647994326110686),
        name: 'undos',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8110973233744550784),
        name: 'bulbs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7752715354692305356),
        name: 'tutorialSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8981744845012209916),
        name: 'lastRuleTutorialLevel',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4285435800749709721),
        name: 'adsRemoved',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 157986918661610179),
        name: 'levelsCompletedCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4024216906167366801),
        name: 'diagonalRuleSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1963020596690680926),
        name: 'minDistanceRuleSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8626051969272955424),
        name: 'knightMoveRuleSeen',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8181293603307300879),
    name: 'SettingsModel',
    lastPropertyId: const obx_int.IdUid(5, 1428176916740032932),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7114717474957569505),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1484279421542001549),
        name: 'musicVolume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6176013920086388741),
        name: 'sfxVolume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9140706585786819276),
        name: 'selectedThemeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1428176916740032932),
        name: 'vibrationEnabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1573346150561790280),
    name: 'DailyChallengeState',
    lastPropertyId: const obx_int.IdUid(5, 8779320624591471531),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6680903058960909970),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4969063995304433250),
        name: 'lastCompletedDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5473270743320550422),
        name: 'currentChallengeStreak',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1633389027231852844),
        name: 'longestChallengeStreak',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8779320624591471531),
        name: 'totalChallengesCompleted',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 1573346150561790280),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DailyRewardState: obx_int.EntityDefinition<DailyRewardState>(
      model: _entities[0],
      toOneRelations: (DailyRewardState object) => [],
      toManyRelations: (DailyRewardState object) => {},
      getId: (DailyRewardState object) => object.id,
      setId: (DailyRewardState object, int id) {
        object.id = id;
      },
      objectToFB: (DailyRewardState object, fb.Builder fbb) {
        final lastClaimDateOffset = fbb.writeString(object.lastClaimDate);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.currentStreakDay);
        fbb.addOffset(2, lastClaimDateOffset);
        fbb.addBool(3, object.claimedToday);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DailyRewardState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..currentStreakDay = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..lastClaimDate = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..claimedToday = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          );

        return object;
      },
    ),
    PlayerProgress: obx_int.EntityDefinition<PlayerProgress>(
      model: _entities[1],
      toOneRelations: (PlayerProgress object) => [],
      toManyRelations: (PlayerProgress object) => {},
      getId: (PlayerProgress object) => object.id,
      setId: (PlayerProgress object, int id) {
        object.id = id;
      },
      objectToFB: (PlayerProgress object, fb.Builder fbb) {
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.normalHighest);
        fbb.addInt64(2, object.hardHighest);
        fbb.addInt64(3, object.ultraHighest);
        fbb.addInt64(4, object.hints);
        fbb.addInt64(5, object.extraLives);
        fbb.addInt64(6, object.undos);
        fbb.addInt64(7, object.bulbs);
        fbb.addBool(8, object.tutorialSeen);
        fbb.addInt64(9, object.lastRuleTutorialLevel);
        fbb.addBool(10, object.adsRemoved);
        fbb.addInt64(11, object.levelsCompletedCount);
        fbb.addBool(12, object.diagonalRuleSeen);
        fbb.addBool(13, object.minDistanceRuleSeen);
        fbb.addBool(14, object.knightMoveRuleSeen);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlayerProgress()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..normalHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..hardHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..ultraHighest = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..hints = const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
          ..extraLives = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..undos = const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
          ..bulbs = const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
          ..tutorialSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..lastRuleTutorialLevel = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..adsRemoved = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            24,
            false,
          )
          ..levelsCompletedCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            26,
            0,
          )
          ..diagonalRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..minDistanceRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            30,
            false,
          )
          ..knightMoveRuleSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            32,
            false,
          );

        return object;
      },
    ),
    SettingsModel: obx_int.EntityDefinition<SettingsModel>(
      model: _entities[2],
      toOneRelations: (SettingsModel object) => [],
      toManyRelations: (SettingsModel object) => {},
      getId: (SettingsModel object) => object.id,
      setId: (SettingsModel object, int id) {
        object.id = id;
      },
      objectToFB: (SettingsModel object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.musicVolume);
        fbb.addFloat64(2, object.sfxVolume);
        fbb.addInt64(3, object.selectedThemeIndex);
        fbb.addBool(4, object.vibrationEnabled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SettingsModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..musicVolume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..sfxVolume = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..selectedThemeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..vibrationEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          );

        return object;
      },
    ),
    DailyChallengeState: obx_int.EntityDefinition<DailyChallengeState>(
      model: _entities[3],
      toOneRelations: (DailyChallengeState object) => [],
      toManyRelations: (DailyChallengeState object) => {},
      getId: (DailyChallengeState object) => object.id,
      setId: (DailyChallengeState object, int id) {
        object.id = id;
      },
      objectToFB: (DailyChallengeState object, fb.Builder fbb) {
        final lastCompletedDateOffset = fbb.writeString(
          object.lastCompletedDate,
        );
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, lastCompletedDateOffset);
        fbb.addInt64(2, object.currentChallengeStreak);
        fbb.addInt64(3, object.longestChallengeStreak);
        fbb.addInt64(4, object.totalChallengesCompleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DailyChallengeState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..lastCompletedDate = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..currentChallengeStreak = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..longestChallengeStreak = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..totalChallengesCompleted = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DailyRewardState] entity fields to define ObjectBox queries.
class DailyRewardState_ {
  /// See [DailyRewardState.id].
  static final id = obx.QueryIntegerProperty<DailyRewardState>(
    _entities[0].properties[0],
  );

  /// See [DailyRewardState.currentStreakDay].
  static final currentStreakDay = obx.QueryIntegerProperty<DailyRewardState>(
    _entities[0].properties[1],
  );

  /// See [DailyRewardState.lastClaimDate].
  static final lastClaimDate = obx.QueryStringProperty<DailyRewardState>(
    _entities[0].properties[2],
  );

  /// See [DailyRewardState.claimedToday].
  static final claimedToday = obx.QueryBooleanProperty<DailyRewardState>(
    _entities[0].properties[3],
  );
}

/// [PlayerProgress] entity fields to define ObjectBox queries.
class PlayerProgress_ {
  /// See [PlayerProgress.id].
  static final id = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[0],
  );

  /// See [PlayerProgress.normalHighest].
  static final normalHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[1],
  );

  /// See [PlayerProgress.hardHighest].
  static final hardHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[2],
  );

  /// See [PlayerProgress.ultraHighest].
  static final ultraHighest = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[3],
  );

  /// See [PlayerProgress.hints].
  static final hints = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[4],
  );

  /// See [PlayerProgress.extraLives].
  static final extraLives = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[5],
  );

  /// See [PlayerProgress.undos].
  static final undos = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[6],
  );

  /// See [PlayerProgress.bulbs].
  static final bulbs = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[7],
  );

  /// See [PlayerProgress.tutorialSeen].
  static final tutorialSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[8],
  );

  /// See [PlayerProgress.lastRuleTutorialLevel].
  static final lastRuleTutorialLevel = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[9],
  );

  /// See [PlayerProgress.adsRemoved].
  static final adsRemoved = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[10],
  );

  /// See [PlayerProgress.levelsCompletedCount].
  static final levelsCompletedCount = obx.QueryIntegerProperty<PlayerProgress>(
    _entities[1].properties[11],
  );

  /// See [PlayerProgress.diagonalRuleSeen].
  static final diagonalRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[12],
  );

  /// See [PlayerProgress.minDistanceRuleSeen].
  static final minDistanceRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[13],
  );

  /// See [PlayerProgress.knightMoveRuleSeen].
  static final knightMoveRuleSeen = obx.QueryBooleanProperty<PlayerProgress>(
    _entities[1].properties[14],
  );
}

/// [SettingsModel] entity fields to define ObjectBox queries.
class SettingsModel_ {
  /// See [SettingsModel.id].
  static final id = obx.QueryIntegerProperty<SettingsModel>(
    _entities[2].properties[0],
  );

  /// See [SettingsModel.musicVolume].
  static final musicVolume = obx.QueryDoubleProperty<SettingsModel>(
    _entities[2].properties[1],
  );

  /// See [SettingsModel.sfxVolume].
  static final sfxVolume = obx.QueryDoubleProperty<SettingsModel>(
    _entities[2].properties[2],
  );

  /// See [SettingsModel.selectedThemeIndex].
  static final selectedThemeIndex = obx.QueryIntegerProperty<SettingsModel>(
    _entities[2].properties[3],
  );

  /// See [SettingsModel.vibrationEnabled].
  static final vibrationEnabled = obx.QueryBooleanProperty<SettingsModel>(
    _entities[2].properties[4],
  );
}

/// [DailyChallengeState] entity fields to define ObjectBox queries.
class DailyChallengeState_ {
  /// See [DailyChallengeState.id].
  static final id = obx.QueryIntegerProperty<DailyChallengeState>(
    _entities[3].properties[0],
  );

  /// See [DailyChallengeState.lastCompletedDate].
  static final lastCompletedDate = obx.QueryStringProperty<DailyChallengeState>(
    _entities[3].properties[1],
  );

  /// See [DailyChallengeState.currentChallengeStreak].
  static final currentChallengeStreak =
      obx.QueryIntegerProperty<DailyChallengeState>(_entities[3].properties[2]);

  /// See [DailyChallengeState.longestChallengeStreak].
  static final longestChallengeStreak =
      obx.QueryIntegerProperty<DailyChallengeState>(_entities[3].properties[3]);

  /// See [DailyChallengeState.totalChallengesCompleted].
  static final totalChallengesCompleted =
      obx.QueryIntegerProperty<DailyChallengeState>(_entities[3].properties[4]);
}
